{
 "title": "Incident Service",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage JVM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_committedHeap_bytes{job=\"incident-service\"}",
     "legendFormat": "Committed Heap {{pod}}"
    },
    {
     "expr": "base_memory_usedHeap_bytes{job=\"incident-service\"}",
     "legendFormat": "Used Heap {{pod}}"
    },
    {
     "expr": "base_memory_maxHeap_bytes{job=\"incident-service\"}",
     "legendFormat": "Max Heap {{pod}}"
    },
    {
     "expr": "vendor_memory_committedNonHeap_bytes{job=\"incident-service\"}",
     "legendFormat": "Committed Non-Heap {{pod}}"
    },
    {
     "expr": "vendor_memory_usedNonHeap_bytes{job=\"incident-service\"}",
     "legendFormat": "Used Non-Heap {pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage OpenShift",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'incident-service-.*',namespace='user1-metrics',container='',}) BY (pod, namespace)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage JVM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent{job=\"incident-service\"}*100",
     "legendFormat": "Process {{pod}}"
    },
    {
     "expr": "vendor_cpu_systemCpuLoad_percent{job=\"incident-service\"}*100",
     "legendFormat": "System {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage OpenShift",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Millicore" }
   ],
   "targets": [
    {
     "expr": "(pod:container_cpu_usage:sum{namespace=\"user1-metrics\", pod=~\"incident-service-.*\"})*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Per Minute" }
   ],
   "targets": [
    {
     "expr": "rate(base_gc_total{job=\"incident-service\"}[1m])*60",
     "legendFormat": "{{ name}} {{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "(rate(base_gc_time_total_seconds{job=\"incident-service\"}[1m])/rate(base_gc_total{job=\"incident-service\"}[1m]))*1000",
     "legendFormat": "{{ name}} {{pod}}"
    }
   ]
  },
  {
   "title": "REST Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "(incident_service:rest:elapsed_time:rate1m/incident_service:rest:total:rate1m)*1000",
     "legendFormat": "{{pod}} {{method}}"
    }
   ]
  },
  {
   "title": "REST Request Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Per second" }
   ],
   "targets": [
    {
     "expr": "incident_service:rest:total:rate1m",
     "legendFormat": "{{pod}} {{method}}"
    }
   ]
  },
  {
   "title": "Repository Operation Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "(incident_service:repository:elapsed_time:rate1m/incident_service:repository:total:rate1m)*1000",
     "legendFormat": "{{pod}} {{operation}}"
    }
   ]
  },
  {
   "title": "Repository Operation Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Per second" }
   ],
   "targets": [
    {
     "expr": "incident_service:repository:total:rate1m",
     "legendFormat": "{{pod}} {{operation}}"
    }
   ]
  },
  {
   "title": "Datasource Pool Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_agroal_max_used_count{job=\"incident-service\"}",
     "legendFormat": "Max Used {{pod}}"
    },
    {
     "expr": "vendor_agroal_available_count{job=\"incident-service\"}",
     "legendFormat": "Available {{pod}}"
    },
    {
     "expr": "vendor_agroal_active_count{job=\"incident-service\"}",
     "legendFormat": "Active {{pod}}"
    },
    {
     "expr": "avg_over_time(vendor_agroal_active_count{job=\"incident-service\"}[1m])",
     "legendFormat": "Average active {{pod}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag over Messages In/Consumed for topic-incident-command",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"incident-service\", topic=\"topic-incident-command\"})",
     "legendFormat": "Offset Lag"
    },
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=\"topic-incident-command\"}[1m]))",
     "legendFormat": "Msg Added"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=\"incident-service\", topic=\"topic-incident-command\"}[1m])/60)",
     "legendFormat": "Msg Consumed"
    }
   ]
  }
 ]
}